version: "3.9"

services:
  backend:
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4

  frontend:
    build:
      context: ./frontend
      target: production
    volumes: []
    ports:
      - "80:80"

  db:
    ports: []
