# Generated by Django 6.0.4 on 2026-04-11 19:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('fitness', 'Fitness'), ('learning', 'Learning'), ('work', 'Work'), ('social', 'Social'), ('health', 'Health'), ('creative', 'Creative'), ('other', 'Other')], default='other', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('xp_gained', models.PositiveIntegerField(default=0)),
                ('logged_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-logged_at'],
            },
        ),
    ]
